# Generated by Django 4.2.3 on 2023-10-30 10:37

import Account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCustomer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_route', models.CharField(choices=[('Area1', 'Area1'), ('Area1B', 'Area1B'), ('Area2', 'Area2'), ('Area3', 'Area3'), ('EastMarket', 'EastMarket'), ('AdissAbabaMarket', 'AdissAbabaMarket'), ('AdissAbabaMarket2', 'AdissAbabaMarket2'), ('Area8', 'Area8'), ('Area1DirectSales', 'Area1DirectSales'), ('AdissAbabaMarket', 'AdissAbabaMarket')], max_length=255)),
                ('tin_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tin_number_doc', models.FileField(blank=True, null=True, upload_to=Account.models.customer_file_path)),
                ('business_license_no', models.CharField(blank=True, max_length=255, null=True)),
                ('business_license_no_doc', models.FileField(blank=True, null=True, upload_to=Account.models.customer_file_path)),
                ('business_registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('business_registration_no_doc', models.FileField(blank=True, null=True, upload_to=Account.models.customer_file_path)),
                ('sales_target', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger', models.IntegerField(blank=True, default=0, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_credit', models.BooleanField(default=False)),
                ('credit_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.TextField(blank=True, max_length=255, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.webcustomer')),
            ],
        ),
    ]
